name: measure_flutter_example
description: "Demonstrates how to use the measure_flutter plugin."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  measure_flutter:
    path: ../packages/measure_flutter
  measure_dio:
    path: ../packages/measure_dio
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8
  stack_trace: ^1.12.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
