name: measure_flutter_example
description: "Demonstrates how to use the measure_flutter plugin."
publish_to: 'none'
version: 0.4.0

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  measure_flutter:
    path: ../packages/measure_flutter
  measure_dio:
    path: ../packages/measure_dio
  dio: ^5.8.0+1
  cupertino_icons: ^1.0.8
  stack_trace: ^1.11.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  measure_build:
    path: ../packages/measure_build/
  build_runner: ^2.4.0

flutter:
  uses-material-design: true