name: Android Checks

on:
  pull_request:
    paths:
      - 'android/**'
      - '!docs/**'
  push:
    branches:
      - 'main'
    paths:
      - 'android/**'
      - '!docs/**'

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: 'temurin'
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  android-checks:
    name: Android SDK checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Run all checks
        run: ./gradlew check

  gradle-plugin-checks:
    name: Gradle Plugin checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'gradle'
      - name: Publish to maven local
        run: ./gradlew :measure:publishToMavenLocal
      - name: Run Gradle plugin checks
        run: ./gradlew :measure-android-gradle:test --no-daemon --no-parallel --no-configuration-cache --stacktrace

  # ensures benchmark app is not broken
  assemble-benchmarks:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'gradle'
      - name: Assemble benchmarks
        run: ./gradlew clean :benchmarks:benchmark:assembleMeasureEnabled --no-daemon --no-parallel --no-configuration-cache --stacktrace -x uploadReleaseBuildToMeasure

  # ensures sample app is not broken
  assemble-sample:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'gradle'
      - name: Assemble sample
        run: ./gradlew clean :sample:assembleRelease --no-daemon --no-parallel --no-configuration-cache --stacktrace -x uploadReleaseBuildToMeasure